name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JavaScript Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: AVID
      - name: Log greeting time
        run: |
          echo "Greeted at: ${{steps.greet.outputs.time}}"

        